Ft bus info
atlp-rwanda/Phantom-Backend-Pirates pull request #32
Opened 2022-03-17 17:49 UTC by JPaul23

2022-03-17 20:45 UTC, David-Neza commented
This branch has conflicts that have to be resolved

2022-03-17 21:00 UTC, christianR15c requested changes

2022-03-17 21:00 UTC, christianR15c commented on README.md
> +>>>>>>> setup project postgres
please review this file

2022-03-17 21:02 UTC, christianR15c requested changes

2022-03-17 21:02 UTC, christianR15c commented on src/controllers/company.js
> +=======
checkout to this file it has unresolved problems

2022-03-18 08:39 UTC, JPaul23 commented on src/controllers/company.js
> +=======
your changes has been addressed

2022-03-18 08:39 UTC, JPaul23 commented on README.md
> +>>>>>>> setup project postgres
your changes has been addressed

2022-03-18 08:45 UTC, christianR15c approved these changes

2022-03-18 10:47 UTC, merged