ft-sockets
atlp-rwanda/Phantom-Backend-Pirates pull request #40
Opened 2022-05-31 09:35 UTC by JPaul23

### What does this PR do?
Add functionality for listening, emitting and broadcasting events between clients(Web APP) and server using `Socket.io` that provides bidirectional and low-latency communication for every platform.
### Why this feature?
To enable sending events from driver dashboard to user map side, to display real-time status of bus across map.
### How was the feature implemented?
This feature was implemented as a sequel of existing bus-simulation, where controls can now send events that can be heard across the application.
### How to test this PR
1. Clone the app both backend and frontend. `git clone {REPOSITORY_URL}` change the {REPOSITY_URL} with the actual link.
2. Run npm install both backend and frontend. `npm install`, this will install all dependencies
3. Edit the **env** to include the *REACT_APP_URL* with the frontend URL.
4. Start backend and frontend servers.
5. Select the routes from /user-map.
6. Start the bus on /simulator.
7. You can stop the bus by pressing Stop button.

Visit [socket.io doc](https://socket.io/docs/v4/)

2022-05-31 17:27 UTC, Anguandia requested changes
Good work @JPaul23 , please resolve the conflicts with develop, then we'll be good to go

2022-05-31 17:27 UTC, Anguandia commented on src/app.js
> +const clients = []
I think we do not really need this for now

2022-05-31 17:27 UTC, Anguandia commented on src/app.js
> +
And theses

2022-05-31 22:09 UTC, Anguandia approved these changes

2022-06-01 04:57 UTC, SimonImanigirimpuhwe approved these changes
LGTM

2022-06-01 04:57 UTC, merged